sudo: required
os:
  - osx
  - linux
dist: focal
env:
  global:
    - COVERALLS_PARALLEL=true
  matrix:
    - PYTHON_VERSION=3.6
    - PYTHON_VERSION=3.7

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update;
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
#  - conda install -y 'libgfortran =3.0.0'
  - conda config --add channels conda-forge
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # test conda can install pyuvdata and python
  - conda install pyuvdata=2.1.1 python="$PYTHON_VERSION"
  # create environment and install dependencies
  - conda install pip h5py matplotlib pyyaml pytest
    pycodestyle coveralls pytest-cov pyuvdata=2.1.1 python="$PYTHON_VERSION"
  - conda list
  - python --version
  # check that the python version matches the desired one; exit immediately if not
  - PYVER=`python -c "from __future__ import print_function; import sys; print('{:d}.{:d}'.format(sys.version_info.major, sys.version_info.minor))"`
  - if [[ $PYVER != $PYTHON_VERSION ]]; then
      exit 1;
    fi
script:
  - python setup.py install
  - pytest --cov=SSINS SSINS/tests/

after_success:
    - coveralls
